### PR TITLE
Modified tests in LP actions yml

### PR DESCRIPTION
**Pull request by D0R11**
# Description

_Please include a summary of changes and related issue (if any)._

# Tests

- [ ] Please provide evidence of your successful `dbt run` / `dbt test` here
- [ ] Any comparison between `prod` and `dev` for any schema change

# Checklist
- [ ] Follow [dbt style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md)
- [ ] Run `git merge main` to pull any changes from remote into your branch prior to merge.
- [ ] Tag the person(s) responsible for reviewing proposed changes
- [ ] **IMPORTANT** Note for deployment if a `full-refresh` is needed for any model this PR impacts.
     - If any schema is changing, whether it be a table or a view, we will need to run a `full-refresh` in prod to avoid errors with the scheduled refresh jobs.
     - The PR can be reviewed, but should not be merged unless by someone with prod access.
         - Tag `forgxyz` if a full-refresh will be required on prod.

### CODE REVIEW

**Review by geewynn — APPROVED** [review]

**Comment by forgxyz** [comment]
I see this is approved, can it be merged?

**Comment by geewynn** [comment]
> I see this is approved, can it be merged?

Waiting on Dorii to revert the nft_mint commits.

**Comment by D0R11** [comment]
> I see this is approved, can it be merged?

Hi Forg, I just removed the excess commits because @liltims77 and I mistakenly put the commits for the NFT mints table here.

**Comment by D0R11** [comment]
This can now be merged.

**Pull request merged**
